import 'app_language.dart';

class LocalizationService {
  AppLanguage language;

  LocalizationService({
    this.language = AppLanguage.tr,
  });

  String text(String key) {
    return _translations[language]?[key] ??
        _translations[AppLanguage.en]?[key] ??
        key;
  }

  static const Map<AppLanguage, Map<String, String>> _translations = {
    AppLanguage.tr: {
      'app_name': 'PowerField Pro',
      'field_mode': 'Saha Modu',
      'expert_mode': 'Uzman Modu',
      'quick_check': 'Hızlı Kontrol',
      'scan_equipment': 'Ekipman Tara',
      'short_circuit': 'Kısa Devre',
      'protection': 'Koruma',
      'cable': 'Kablo',
      'load_flow': 'Yük Akışı',
      'equipment': 'Ekipman',
      'report': 'Rapor',
      'standard': 'Standart',
      'country': 'Ülke',
      'language': 'Dil',
      'why': 'Neden?',
      'pass': 'Uygun',
      'warning': 'Uyarı',
      'fail': 'Uygun Değil',
      'not_verified': 'Doğrulanmadı',
    },

    AppLanguage.en: {
      'app_name': 'PowerField Pro',
      'field_mode': 'Field Mode',
      'expert_mode': 'Expert Mode',
      'quick_check': 'Quick Check',
      'scan_equipment': 'Scan Equipment',
      'short_circuit': 'Short Circuit',
      'protection': 'Protection',
      'cable': 'Cable',
      'load_flow': 'Load Flow',
      'equipment': 'Equipment',
      'report': 'Report',
      'standard': 'Standard',
      'country': 'Country',
      'language': 'Language',
      'why': 'Why?',
      'pass': 'Pass',
      'warning': 'Warning',
      'fail': 'Fail',
      'not_verified': 'Not Verified',
    },

    AppLanguage.fr: {
      'app_name': 'PowerField Pro',
      'field_mode': 'Mode Terrain',
      'expert_mode': 'Mode Expert',
      'quick_check': 'Contrôle Rapide',
      'scan_equipment': 'Scanner Équipement',
      'short_circuit': 'Court-Circuit',
      'protection': 'Protection',
      'cable': 'Câble',
      'load_flow': 'Flux de Puissance',
      'equipment': 'Équipement',
      'report': 'Rapport',
      'standard': 'Norme',
      'country': 'Pays',
      'language': 'Langue',
      'why': 'Pourquoi ?',
      'pass': 'Conforme',
      'warning': 'Avertissement',
      'fail': 'Non Conforme',
      'not_verified': 'Non Vérifié',
    },

    AppLanguage.de: {
      'app_name': 'PowerField Pro',
      'field_mode': 'Feldmodus',
      'expert_mode': 'Expertenmodus',
      'quick_check': 'Schnellprüfung',
      'scan_equipment': 'Gerät Scannen',
      'short_circuit': 'Kurzschluss',
      'protection': 'Schutz',
      'cable': 'Kabel',
      'load_flow': 'Lastfluss',
      'equipment': 'Gerät',
      'report': 'Bericht',
      'standard': 'Norm',
      'country': 'Land',
      'language': 'Sprache',
      'why': 'Warum?',
      'pass': 'Bestanden',
      'warning': 'Warnung',
      'fail': 'Nicht Bestanden',
      'not_verified': 'Nicht Verifiziert',
    },

    AppLanguage.es: {
      'app_name': 'PowerField Pro',
      'field_mode': 'Modo Campo',
      'expert_mode': 'Modo Experto',
      'quick_check': 'Comprobación Rápida',
      'scan_equipment': 'Escanear Equipo',
      'short_circuit': 'Cortocircuito',
      'protection': 'Protección',
      'cable': 'Cable',
      'load_flow': 'Flujo de Carga',
      'equipment': 'Equipo',
      'report': 'Informe',
      'standard': 'Norma',
      'country': 'País',
      'language': 'Idioma',
      'why': '¿Por qué?',
      'pass': 'Correcto',
      'warning': 'Advertencia',
      'fail': 'No Conforme',
      'not_verified': 'No Verificado',
    },

    AppLanguage.zh: {
      'app_name': 'PowerField Pro',
      'field_mode': '现场模式',
      'expert_mode': '专家模式',
      'quick_check': '快速检查',
      'scan_equipment': '扫描设备',
      'short_circuit': '短路',
      'protection': '保护',
      'cable': '电缆',
      'load_flow': '潮流',
      'equipment': '设备',
      'report': '报告',
      'standard': '标准',
      'country': '国家',
      'language': '语言',
      'why': '为什么？',
      'pass': '通过',
      'warning': '警告',
      'fail': '不符合',
      'not_verified': '未验证',
    },

    AppLanguage.ru: {
      'app_name': 'PowerField Pro',
      'field_mode': 'Полевой режим',
      'expert_mode': 'Экспертный режим',
      'quick_check': 'Быстрая проверка',
      'scan_equipment': 'Сканировать оборудование',
      'short_circuit': 'Короткое замыкание',
      'protection': 'Защита',
      'cable': 'Кабель',
      'load_flow': 'Поток мощности',
      'equipment': 'Оборудование',
      'report': 'Отчёт',
      'standard': 'Стандарт',
      'country': 'Страна',
      'language': 'Язык',
      'why': 'Почему?',
      'pass': 'Соответствует',
      'warning': 'Предупреждение',
      'fail': 'Не соответствует',
      'not_verified': 'Не проверено',
    },

    AppLanguage.ja: {
      'app_name': 'PowerField Pro',
      'field_mode': '現場モード',
      'expert_mode': 'エキスパートモード',
      'quick_check': 'クイックチェック',
      'scan_equipment': '機器をスキャン',
      'short_circuit': '短絡',
      'protection': '保護',
      'cable': 'ケーブル',
      'load_flow': '潮流',
      'equipment': '機器',
      'report': 'レポート',
      'standard': '規格',
      'country': '国',
      'language': '言語',
      'why': '理由',
      'pass': '適合',
      'warning': '警告',
      'fail': '不適合',
      'not_verified': '未検証',
    },
  };
}
